### ISSUE TITLE
Suggestions box row height is too short

### ISSUE THREAD

**Issue by vijaykharage** [JohnSundell/XcodeTheme#6]
Hi John, I love your xcode theme. Thanks BTW. 
I am facing little trouble while reading the suggested methods. Can you help me to increase the height of row?
![screen shot 2018-06-22 at 4 53 27 pm](https://user-images.githubusercontent.com/31646541/41774416-45bdd9c6-763d-11e8-86e9-b14b4add32ee.png)

**Comment by JohnSundell** [comment]
I don't know what's causing that problem, but I doubt that it's a problem with the theme (Xcode themes just define colors and fonts, not the size of UI elements). Since you have a red highlight it looks like some other form of customization. Maybe you have some plugins that are interfering with the dialog? Here's what that same dialog looks like for me:

<img width="1332" alt="dialog" src="https://user-images.githubusercontent.com/2466701/41841935-d6e333c8-7869-11e8-94b4-9a7a3e501b27.png">

Won't be able to assist you further on this, so closing this issue. Hope you find a solution 🙂
